sonar.projectKey=CharfeddineMahdi_Serenite
sonar.organization=charfeddinemahdi

sonar.sources=lib
sonar.tests=test

# Coverage
sonar.dart.lcov.reportPaths=coverage/lcov.info

# ? Disable native code analysis
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Serenite
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8